apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nowline-production
resources:
  - ../../base
  - namespace.yaml
  - service-accounts.yaml
  - ingress.yaml
  - frontend-pdb.yaml
  - network-policies.yaml
  - monitoring.yaml
patches:
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nowline-backend
    patch: |-
      - op: remove
        path: /spec/template/spec/initContainers
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: nowline-mysql
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: nowline-mysql
  - target:
      version: v1
      kind: Service
      name: nowline-mysql
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: nowline-mysql
images:
  - name: nowline-backend
    newName: ghcr.io/jieseob1/planner-backend
    newTag: 0.1.0
  - name: nowline-frontend
    newName: ghcr.io/jieseob1/planner-frontend
    newTag: 0.1.0
