apiVersion: v1
kind: ServiceAccount
metadata:
  name: nowline-backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nowline-frontend
automountServiceAccountToken: false
