apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nowline-local
resources:
  - namespace.yaml
  - ../../base
  - keycloak.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: nowline
    app.kubernetes.io/component: database-credentials
configMapGenerator:
  - name: nowline-keycloak-realm
    files:
      - files/nowline-realm.json
  - name: nowline-keycloak-bootstrap
    files:
      - files/bootstrap-keycloak.sh
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nowline-backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NOWLINE_OIDC_ISSUER
          value: http://localhost:4189/idp/realms/nowline
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NOWLINE_OIDC_AUDIENCE
          value: nowline-api
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NOWLINE_OIDC_JWK_SET_URI
          value: http://nowline-keycloak:8080/idp/realms/nowline/protocol/openid-connect/certs
images:
  - name: nowline-backend
    newName: nowline-backend
    newTag: local
  - name: nowline-frontend
    newName: nowline-frontend-beta
    newTag: local
  - name: nowline-keycloak
    newName: nowline-keycloak
    newTag: local
