import { act, renderHook, waitFor } from '@testing-library/react';
import type { PropsWithChildren } from 'react';
import { afterEach, expect, it, vi } from 'vitest';
import { plannerApi } from '../api/plannerApi';
import { createEmptySnapshot } from '../data/empty';
import { PlannerProvider, usePlanner } from './PlannerProvider';
vi.mock('../auth/AuthProvider', () => ({ useAuth: () => ({ subject: 'test:completed-at' }) }));
vi.mock('../timezone/TimeZoneProvider', () => ({ useTimeZone: () => ({ timeZone: 'Asia/Seoul' }) }));
afterEach(() => { vi.restoreAllMocks(); vi.useRealTimers(); });
it('keeps check-off time while editing and replaces it only after undo and re-completion', async () => {
  localStorage.clear();
  const snapshot = createEmptySnapshot('Asia/Seoul');
  snapshot.tasks = [{ id: 't', title: '타이머 없이 완료', status: 'todo', outcomeId: null, estimateMinutes: 25, pinned: false, carryCount: 0 }];
  vi.spyOn(plannerApi, 'get').mockResolvedValue({ kind: 'found', aggregate: { revision: 1, snapshot }, etag: '"planner-test-1"' });
  vi.spyOn(plannerApi, 'put').mockImplementation(async (s) => ({ aggregate: { revision: 2, snapshot: s }, etag: '"planner-test-2"' }));
  const wrapper = ({ children }: PropsWithChildren) => <PlannerProvider>{children}</PlannerProvider>;
  const { result } = renderHook(() => usePlanner(), { wrapper });
  await waitFor(() => expect(result.current.saveStatus).toBe('saved'));
  vi.useFakeTimers({ toFake: ['Date'] }); vi.setSystemTime(new Date('2026-09-07T05:00:00Z'));
  act(() => result.current.updateTask('t', { status: 'done' }));
  expect(result.current.tasks[0].completedAt).toBe('2026-09-07T05:00:00.000Z');
  act(() => result.current.updateTask('t', { title: '제목만 수정' }));
  expect(result.current.tasks[0].completedAt).toBe('2026-09-07T05:00:00.000Z');
  act(() => result.current.updateTask('t', { status: 'todo' }));
  expect(result.current.tasks[0].completedAt).toBeUndefined();
  vi.setSystemTime(new Date('2026-09-08T05:00:00Z'));
  act(() => result.current.updateTask('t', { status: 'done' }));
  expect(result.current.tasks[0].completedAt).toBe('2026-09-08T05:00:00.000Z');
});
