import { act, renderHook, waitFor, cleanup } from '@testing-library/react';
import type { PropsWithChildren } from 'react';
import { afterEach, expect, it, vi } from 'vitest';
import { plannerApi } from '../api/plannerApi';
import { createEmptySnapshot } from '../data/empty';
import { PlannerProvider, usePlanner, getPlannerStorageKeys } from './PlannerProvider';
vi.mock('../auth/AuthProvider', () => ({ useAuth: () => ({ subject: 'test:subtasks' }) }));
vi.mock('../timezone/TimeZoneProvider', () => ({ useTimeZone: () => ({ timeZone: 'Asia/Seoul' }) }));
afterEach(() => { cleanup(); vi.restoreAllMocks(); });

it('persists checklist edits without double-counting work and keeps them when removing only a schedule', async () => {
  localStorage.clear();
  let snapshot = createEmptySnapshot('Asia/Seoul');
  snapshot.tasks = [{ id: 't', title: '할 일', status: 'todo', outcomeId: null, estimateMinutes: 60, pinned: false, carryCount: 0 }];
  let revision = 1;
  vi.spyOn(plannerApi, 'get').mockImplementation(async () => ({ kind: 'found', aggregate: { revision, snapshot }, etag: `"planner-test-${revision}"` }));
  vi.spyOn(plannerApi, 'put').mockImplementation(async s => { snapshot = s; revision++; return { aggregate: { revision, snapshot }, etag: `"planner-test-${revision}"` }; });
  const wrapper = ({ children }: PropsWithChildren) => <PlannerProvider>{children}</PlannerProvider>;
  const first = renderHook(() => usePlanner(), { wrapper });
  await waitFor(() => expect(first.result.current.saveStatus).toBe('saved'));
  act(() => { expect(first.result.current.updateTask('t', { subtasks: [{ id: 's', title: '  세부 작업  ', done: true }] })).toBe(true); });
  expect(first.result.current.tasks[0]).toMatchObject({ status: 'todo', subtasks: [{ title: '세부 작업', done: true }] });
  expect(first.result.current.tasks).toHaveLength(1);
  expect(first.result.current.timeEntries).toHaveLength(0);
  await waitFor(() => expect(plannerApi.put).toHaveBeenCalled());
  await waitFor(() => expect(first.result.current.saveStatus).toBe('saved'));
  first.unmount();
  const second = renderHook(() => usePlanner(), { wrapper });
  await waitFor(() => expect(second.result.current.saveStatus).toBe('saved'));
  expect(second.result.current.tasks[0].subtasks?.[0].title).toBe('세부 작업');
  act(() => second.result.current.updateTask('t', { status: 'done' }));
  act(() => second.result.current.updateTask('t', { status: 'todo' }));
  expect(second.result.current.tasks[0].subtasks?.[0].done).toBe(true);
  act(() => { expect(second.result.current.updateTask('t', { subtasks: [{ id: 's', title: '', done: false }] })).toBe(false); });
  act(() => second.result.current.saveTimeBlock({ taskId: 't', title: '할 일', day: 'mon', startMinutes: 600, durationMinutes: 60, date: '2026-09-07' }));
  act(() => second.result.current.removeTimeBlock(second.result.current.timeBlocks[0].id));
  expect(second.result.current.tasks[0].subtasks).toHaveLength(1);
  act(() => second.result.current.updateTask('t', { subtasks: [] }));
  expect(second.result.current.tasks[0].subtasks).toEqual([]);
  expect(JSON.parse(localStorage.getItem(getPlannerStorageKeys('test:subtasks').snapshot)!).tasks[0].subtasks).toEqual([]);
});
